language: python
python:
- 3.4
install:
- pip install --upgrade pip
- pip install ruamel.yaml==0.10.10
- pip install coveralls
- pip install https://github.com/missionpinball/mpf/zipball/dev

before_script:
 - export PYTHONPATH=$PYTHONPATH:$(pwd)

script: coverage run -m unittest discover

after_success: coveralls
